### PR TITLE
V1.0.0

### PR DESCRIPTION
**Pull request by 3D-I**
Let it be an extension.

Stand-alone, for general extension writers purposes.

### CODE REVIEW

**Comment by javiexin** [comment]
Thanks a lot Marco.  I have things to iron out before releasing, but it is in the good track :)
Now, the comments.
Why README.md is duplicated?  We should only keep one... at the root maybe.
For the listener, we probably do not need the switch, so we may very well remove it: if the extension is enabled, it will be there.  If not enabled, it won't, and will not show up.
For dependency tracking, I'd rather do what I proposed in the phpbb thread, so hold it for now (config var and the likes).
And finally, the library placement, should be simpler: either directly under template (as forum_fn.js) or in a generic place, like js or lib folders, but not yet another jxtools in the folder name :)
And the comments in the header of the library and the examples could go to the README.md file as well (examples maybe should not go in the actual extension).

**Comment by 3D-I** [comment]
I see, I will update the PR as soon as I can. About the switch, there it was a reason why is there because I wrote this PR after a lot of considerations about it.. let me recall the reason why though.

**Comment by 3D-I** [comment]
Ok, now fits to what you commented above.
The switch it was for an idea I had but actually we don't need it, for now at least.

**Comment by 3D-I** [comment]
Hello Javier, I think this extension should be released as it is with this PR, the check if this extension is installed should be done first into your main ext (ext.php using extension manager) and then within your "use cases" extension (always in ext.php the same way). It doesn't harm to have this ext as a stand-alone one which benefits potentially many extension writers.
Not to mention it could be submitted right now to the CDB ans save some time before we will sort out the method you are thinking of.

The extension manager offers a lot of functions to be used on purpose, I did studied it a bit.
Just I am not having so much time to expand on my thoughts.

Regards.

**Comment by javiexin** [comment]
Ciao Marco,
I am not planning to release the library just yet: I am about to release a
"dev" extension for "Dependency Management" on 3.1.11 (new events
required), and I will wait for that before I have JxTools as its own
extension.
That way, whoever wants to use the library could just create a dependency
on it, and have the Dependency Manager maintain it.
Thanks for your help and interest!
-javiexin

**Comment by 3D-I** [comment]
Fine, thanks Javier.

Happy Holydays.
- Marco

**Comment by 3D-I** [comment]
HI Javier, the extension using this library has been validated.
Means also your code has been. I got no reference to the CR issues.

What are your plans for this, now?

Marco

**Comment by javiexin** [comment]
I might consider releasing it (I want to), but not sure if an extension is the right approach...
Anyhow, any more functionality that may be useful here before we do a public announcement?
I was thinking in actions to copy/paste CSS properties across the DOM, and add/remove classes to facilitate interaction with CSS rules.

**Comment by 3D-I** [comment]
It is up to you, you are the expert here from which I am learning. I think is a good idea though.
I wanted you to be informed that eveything went well, and thank you.
Perhaps the file with CR issues got no problems because I saved it back with my IDE. I guess.

**Comment by 3D-I** [comment]
RIP mate, I will take care of this.

**Pull request closed without merging**
